---
target: local

# License key
newrelic_license_key: False

ferm_ansible_controllers: ['127.0.0.1']

mysql_mysqld_allow: [ "ALL" ]
mysql_mysqld_bind_address: '0.0.0.0'

webhost: local
apache_host: "192.168.50.10"
allow_override_htaccess: None

app_env:
  aliases: []
  user: 'vagrant'
  group: 'www-data'
  admin_email: admin@drupsible.org
  fpm_listen: '/var/run/php5-fpm-{{ app_name }}.sock'
  files_tarball_filename: "{{ app_name }}-files.tar.gz"
  db_name: drupsible
  db_user: "{{ app_name }}"
  # Set to True if the target env has memcached available
  memcached: True
  # True clones the cur database
  db_clone: False
  # True looks for a DB dump to upload and import
  db_import: False
  # True syncs with source DB
  db_sync: True
  # True looks for tarballs (files) to upload and import
  files_import: False
  files_sync: False
  files_copy: False
  do_cur_backup: False
  adjust_db: False
  syslog: True

drupal_admin_password: "drups1ble"

app_drush_source:
  # Source settings for initial import
  docroot: '/var/www/drupsible/public_html'
  remote_host: 'www.drupsible.org'
  remote_user: 'drupsible'
  remote_port: 22
  ssh_options: '-o ForwardAgent=yes'
