php5_packages:
  - php-pear
  - php-soap
  - php5-curl
  - php5-gd
  - php5-gmp
  - php5-mcrypt
  - php5-memcached
  - php5-mysql

php5_post_max_size: '32M'

php5_default_pm_status: True
php5_default_pm_status_path: "{{ server_status_path | default('status')}}"
php5_default_ping_path: "{{ ping_path | default('ping') }}"

app_php5_production: "{{ (target == 'prod') | ternary(true, false) }}"

php_value:
  memory_limit: 192M
  newrelic_appname: "{{ app_name }}"
  max_input_vars: 2000
  # The following settings for PHP 5.5 are based on https://goo.gl/AsDmgt
  opcache.memory_consumption: 64 # MB, adjust to your needs
  opcache.max_accelerated_files: 6000 # Adjust to your needs
  opcache.max_wasted_percentage: 10 # Adjust to your needs
  
php_flag:
  cgi.fix_path_info: 1
  # The following settings for PHP 5.5 are based on https://goo.gl/AsDmgt
  opcache.validate_timestamps: "{{ (target == 'prod') | ternary('0', '1') }}"
  opcache.fast_shutdown: 1
