---
# from github
- src: https://github.com/mbarcia/drupsible-apache
  version: master
  name: drupsible.apache2
- src: https://github.com/mbarcia/drupsible-memcached
  version: master
  name: drupsible.memcached
- src: https://github.com/mbarcia/drupsible-newrelic
  version: master
  name: drupsible.newrelic
- src: https://github.com/mbarcia/drupsible-composer
  version: master
  name: drupsible.composer
- src: https://github.com/mbarcia/drupsible-drush
  version: master
  name: drupsible.drush
- src: https://github.com/mbarcia/drupsible-mysql
  version: master
  name: drupsible.mysql
- src: https://github.com/mbarcia/drupsible-deploy
  version: master
  name: drupsible.deploy
